import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

const ICON_DIR = resolve(__dirname, '../public/icons')
const PNG_MAGIC = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]

/** Read a PNG's IHDR width/height (bytes 16-24, big-endian). */
function pngSize(bytes: Buffer): { w: number; h: number } {
  return { w: bytes.readUInt32BE(16), h: bytes.readUInt32BE(20) }
}

const CASES: { file: string; size: number }[] = [
  { file: 'icon-192.png', size: 192 },
  { file: 'icon-512.png', size: 512 },
  { file: 'icon-maskable-512.png', size: 512 }
]

describe('PWA icons (generated by scripts/gen-icon.mjs)', () => {
  for (const { file, size } of CASES) {
    it(`${file} exists, is a PNG, and is ${size}x${size}`, () => {
      const path = resolve(ICON_DIR, file)
      expect(existsSync(path)).toBe(true)
      const bytes = readFileSync(path)
      expect([...bytes.subarray(0, 8)]).toEqual(PNG_MAGIC)
      expect(pngSize(bytes)).toEqual({ w: size, h: size })
    })
  }
})
